apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: mmkusma/gitopsfc
  newTag: cdf9d0ecec580c43d29d246f9808e7f5d98ab04f
