name: CDGitops

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build_auth
      uses: docker/build-push-action@v3
      with:
       context: .
       file: Dockerfile
       push: true
       tags: |
        ${{ secrets.DOCKERHUB_USERNAME }}/gitopsfc:latest
        ${{ secrets.DOCKERHUB_USERNAME }}/gitopsfc:${{ github.sha }}
    
    # - name: Build and push image to Dockerhub
    #   uses: docker/build-push-action@v1.1.0
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     repository: ${{ secrets.DOCKERHUB_USERNAME }}/gitopsfc
    #     tags: ${{ github.sha }}, latest

